### ISSUE TITLE
Nonce

### ISSUE THREAD

**Issue by glaucoheitor** [dutu/poloniex-api-node#19] opened 2017-07-11 01:46 UTC
I don't know if it my implementation mistake, but I am running into nonce problems very often.

I check the ticker every 1.5s and when certain cenario appear I make a buy. Sometimes i might send 5 buys every 1.5s and that's where i got into problems like sending the same nonce in every request and getting mutiple EQUAL erros like these:

Error: Poloniex error 422: . Nonce must be greater than 149973383738800. You provided 149973383730200.

also, I use one API key for each action: one for ticker, one for buy, one for checking balance, etc.

**Comment by dutu** [comment] 2017-07-11 07:13
@glaucoheitor Poloniex requires the nonce parameter as an integer which must always be greater than the nonce used in previous API call.

This library is achieving an ever increasing nonce for each API call by using module [nonce](https://www.npmjs.com/package/nonce), which uses UNIX timestamp in milliseconds.

I suggest you open a support ticket with Poloniex to discuss your scenario and find out why Poloniex is issuing nonce errors.

NB: one way of resolving the issue is to place a next buy order only when the previous one has received the response from Poloniex. (You could achieve this by using an async library). The drawback is that recently Poloniex API calls take several seconds to execute (at times up to 30-60 seconds), hence 5 buy orders may take a few minutes to complete.

I would appreciate if you update this issue here once you receive an answer from Poloniex support.

**Comment by glaucoheitor** [comment] 2017-07-11 16:30
I understand all that. I just don't understand why two different actions using your wrapper are sending the same nonce. I am sure it isnt sending at the same milisecond.

The new "keepalive" param have anything to do with it?

Thank you.

**Comment by dutu** [comment] 2017-07-12 10:17
I don't see how the same nonce can be sent at different time frames. 
A new nonce is generated at each call: 
https://github.com/dutu/poloniex-api-node/blob/master/lib/poloniex.js#L175

Could you perhaps insert after line 175 the command `console.log(JSON.stringify(params))` and share the logs?

**Comment by martmull** [comment] 2017-07-20 19:47
I tried the API today and I also have problems with nonces. The API seems to provide nonce 10 time lower the required once, for example :

"Poloniex error 422: . Nonce must be greater than 1500417741735932. You provided 150057913685600."

I just multiply by 10 the line 175 : `param.nonce = 10*nonce(16);` (I didn't commit that)
It seems to work for now, but doesn't explain why nonce() returns a wrong value...

**Comment by dutu** [comment] 2017-07-22 12:53
closing this due to no response and it doesn't seem to be an issue with the module.

**Closed by dutu** 2017-07-22 12:53 UTC
Labels: question
